server:
  port: 16081
  servlet:
    context-path: /validator-oss
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 5
    host: 192.168.0.234
    port: 6379
    password: Root123~
    lettuce:
      pool:
        #最大连接数
        max-active: 2048
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 1024
        #最小空闲
        min-idle: 512
    timeout: 1000